# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4d472b3a5a20811d53ffb2fa8bccd3329a201afd640f88ef3584a7846076cb67ca19943ec521db2ee1669e5ec6c318771aa8cf59bcafaf6fbcdaf2c573d18ead

test:
  secret_key_base: 1227377d3c758546c3444ebc67bb03a7fc2dbd05987b06a207f1edd3392e81e698b8f60fdad0a77e9d53d8cf6015ef23c668ff0982a86b71b8c057afb12e8508

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
